version: "3.2"
services:
    postgres-15:
        container_name: postgres-15
        image: postgres:15-alpine
        ports:
            - 5432:5432
        volumes:
            - ~/.postgres/data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: "p@ssw0rd"
            POSTGRES_USER: "yanoo"
            ACCEPT_EULA: "Y"
